{% set name = "spqr" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8713ea89fb6e9c364ff5c6a387af9a7cb21a4e7cc27d1c969c606ec119672994

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - SPQR
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://pypi.org/project/SPQR/
  summary: 'Roman numerals in your interpreter'
  description: |
    Still Partially Quompatible with Roman empire allow you to deals with numeral use a long time ago in the BF times
    (BF as Before Fortran). As you all know the necessity for quick iteration as for long been a goal in the scientific
    community, as well a reproducibility and backward compatibility. Now you can quickly achieve the efficiency you had
    to engrave number on you marble tablet calculator from the comfort of your QWERTY keyboard, and replicate studies
    made at the time of Neron, Ceasar, and all thoses guy you don't remember the name.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/carreau/SPQR

extra:
  recipe-maintainers:
    - Carreau
